plugins:
  - jekyll-seo-tag
  - jekyll-feed

social:
  name: Tobias Klöpper
  links:
    - https://twitter.com/friendscover
    - https://github.com/Friendscover
    - https://www.linkedin.com/in/tobias-kl%C3%B6pper-b054701ba/
    - https://www.polywork.com/friendscover

title: Tobias Klöppers Blog
tagline: A blog about coding and agriculture. So
locale: en_DE