plugins:
  - jekyll-seo-tag
  - jekyll-feed

social:
  name: Tobias Klöpper
  links:
    - https://github.com/Friendscover
    - https://www.linkedin.com/in/tobias-kl%C3%B6pper-b054701ba/
    - https://codeberg.org/friendscover
    - https://mastodon.social/@friendscover

title: Tobias Klöppers Blog
tagline: A blog about coding and agriculture.
locale: en_DE